document.write( '<!DOCTYPE html>\n' );
document.write( '<html lang=\"pt-br\">\n' );
document.write( '    <head>\n' );
document.write( '        <meta charset=\"UTF-8\">\n' );
document.write( '        <title>Barbearia Alura</title>\n' );
document.write( '        <link rel=\"stylesheet\" href=\"style.css\">\n' );
document.write( '    </head>\n' );
document.write( '\n' );
document.write( '    <body>\n' );
document.write( '        <header>\n' );
document.write( '            <h1 class=\"titulo principal\">Barbearia Alura</h1>\n' );
document.write( '        </header>\n' );
document.write( '        <img id=\"banner\" src=\"banner.jpg\"\n' );
document.write( '        <div class=\"principal\">\n' );
document.write( '          <h2 class=\"titulo-centralizado\">Sobre a Barbearia Alura</h2>\n' );
document.write( '\n' );
document.write( '    <p>Localizada no coração da cidade a <strong>Barbearia Alura</strong> traz para o mercado o que há de melhor para o seu cabelo e barba. \n' );
document.write( '    Fundada em 2019, a Barbearia Alura já é destaque na cidade e conquista novos clientes a cada dia.</p>\n' );
document.write( '\n' );
document.write( '    <p id=\"missao\"><em>Nossa missão é: <strong>\"Proporcionar auto-estima e qualidade de vida aos clientes\"</strong>.</em></p>\n' );
document.write( '\n' );
document.write( '    <p>Oferecemos profissionais experientes e antenados às mudanças no mundo da moda. \n' );
document.write( '    O atendimento possui padrão de excelência e agilidade, garantindo qualidade e satisfação dos nossos clientes.</p>\n' );
document.write( '</div>\n' );
document.write( ' <div class=\"beneficios\">\n' );
document.write( '    <h3>Benefícios</h3>\n' );
document.write( '\n' );
document.write( '    <ul>\n' );
document.write( '        <li class=\"itens\">Atendimento aos Clientes</li>\n' );
document.write( '        <li class=\"itens\">Espaço diferenciado</li>\n' );
document.write( '        <li class=\"itens\">Localização</li>\n' );
document.write( '        <li class=\"itens\">Profissionais Qualificados</li>\n' );
document.write( '    </ul>\n' );
document.write( '\n' );
document.write( '    <img src=\"beneficios.jpg\" class=\"imagembeneficios\">\n' );
document.write( '</div>\n' );
document.write( '\n' );
document.write( '    ' );
